### PR TITLE
Convert diagram files into lutaml

### PR DESCRIPTION
**Pull request by w00lf**
metanorma/basicdoc-models#17 convert all wsd files into lutaml files, change diagram images into lutaml converted

@ronaldtse  converted wsd files into lutaml, also converted images with lutaml, I have left the original images to compare. There are some issues:
- in models/BibData.wsd one of the classes has  <<Bibliography>> modifier, lutaml does not support yet such modifier
- comments blocks cannot be displayed with graphviz
- difference in display styling

### CODE REVIEW

**Comment by ronaldtse** [comment]
> in models/BibData.wsd one of the classes has <> modifier, lutaml does not support yet such modifier

The <> is the package? Do we support packages?

**Comment by w00lf** [comment]
> > in models/BibData.wsd one of the classes has <> modifier, lutaml does not support yet such modifier
> 
> The <> is the package? Do we support packages?

Lutaml-uml does not support packages yet

**Comment by w00lf** [comment]
> > in models/BibData.wsd one of the classes has <> modifier, lutaml does not support yet such modifier
> 
> The <> is the package? Do we support packages?

Added support for custom keywords, models/BibData.wsd and others now displayed correctly, removed old wsd files.

**Comment by ronaldtse** [comment]
@w00lf can you help remove all the `dot` files so that the `png`s are directly generated? Thanks.

**Comment by w00lf** [comment]
> @w00lf can you help remove all the `dot` files so that the `png`s are directly generated? Thanks.

done, removed

**Comment by ronaldtse** [comment]
Thank you @w00lf !

**Pull request merged**
